# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]


jobs:      
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Flutter Install
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Check Flutter
        run: flutter doctor

      - name: Build APK (Android)
        run: flutter build apk --debug

      - name: Upload APK artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: build/app/outputs/apk/debug/app-debug.apk

      - name: Run tests
        run: flutter test


  firebase:
    name: Run UI tests with Firebase Test Lab
    needs: apk
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug

      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk --device model=Pixel5,version=30,locale=pl,orientation=portrait
