# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Flutter Install
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Check Flutter
        run: flutter doctor

      - name: Build APK (Android)
        run: flutter build apk --debug

      - name: Upload APK artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: build/app/outputs/apk/debug/app-debug.apk

      - name: Run tests
        run: flutter test
