# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]


jobs:      
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Flutter Install
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          
      - name: Check Flutter
        run: flutter doctor

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Change directory to android
        run: |
              pushd android
              flutter build apk
              bash ./gradlew app:assembleAndroidTest
              bash ./gradlew app:assembleDebug -Ptarget=integration_test/integration_test.dart
              popd
        
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: build/app/outputs/apk/debug/app-debug.apk

      - name: Upload Test APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-androidTest.apk
          path: build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk
        
      - name: Download debug APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug.apk

      - name: Download Android test APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest.apk

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH_JSON }}'

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Check Flutter
        run: ls

     # Run the Firebase Test Lab Action
      - name: Run tests on Firebase Test Lab
        run: gcloud firebase test android run --type robo --app ./app-debug.apk --device model=Pixel2,version=28,locale=pl,orientation=portrait
